#! /usr/bin/env python3

# Core packages
import argparse
import pkg_resources
import sys

# Local packages
from canonicalwebteam import dotrun

# Parse arguments
parser = argparse.ArgumentParser(
    description='Upload assets from this directory'
)
parser.add_argument('command',  nargs="?", help="Choose which command to run")
parser.add_argument(
    '-v', '--version',
    action='store_true',
    help="Show the currently installed version of documentation-builder."
)
cli_arguments = vars(parser.parse_args())

# Process arguments
if cli_arguments['version']:
    print(
        pkg_resources.get_distribution(
            "canonicalwebteam.dotrun"
        ).version
    )
elif cli_arguments['command'] == 'list':
    dotrun.list_projects()
elif cli_arguments['command'] == 'serve':
    dotrun.serve()
else:
    parser.print_help()
