#! /usr/bin/env bash

set -exuo pipefail

multipass launch -n test-dotrun bionic || echo "Skipping..."
multipass start test-dotrun

# Install snapcraft
multipass exec test-dotrun -- sudo apt-get update
multipass exec test-dotrun -- sudo apt-get install --yes python3-pip
multipass exec test-dotrun -- sudo snap install snapcraft --classic
multipass exec test-dotrun -- sudo ln -fs /snap/bin/snapcraft /usr/bin/snapcraft

# Copy files into VM (remove any old files)
tar -czO . | multipass transfer - test-dotrun:dotrun.tar.gz
multipass exec test-dotrun -- rm -rf ./dotrun
multipass exec test-dotrun -- sudo locale-gen en_GB.UTF-8
multipass exec test-dotrun -- sudo update-locale LANG=en_GB.UTF-8
multipass exec test-dotrun -- mkdir -p ./dotrun
multipass exec test-dotrun -- tar -C ./dotrun -xzf dotrun.tar.gz

# Build and install snap
multipass exec test-dotrun -- sh -c "rm -rf ./dotrun/dotrun_*.snap"
multipass exec test-dotrun -- sh -c "cd ./dotrun && snapcraft --destructive-mode"
multipass exec test-dotrun -- sh -c "sudo snap install --dangerous ./dotrun/dotrun_*.snap"
multipass exec test-dotrun -- sh -c "sudo snap connect dotrun:dot-npmrc"
multipass exec test-dotrun -- sh -c "sudo snap connect dotrun:dot-yarnrc"
multipass exec test-dotrun -- sh -c "echo 'export PATH=/snap/bin:$PATH' > .bashrc"

# Run tests against installed snap
multipass exec test-dotrun -- touch .npmrc  # Ensure npmrc file exists, as it may for users
multipass exec test-dotrun -- touch .yarnrc  # Ensure yarnrc file exists, as it may for users
multipass exec test-dotrun -- pip3 install ipdb  # For debugging tests
multipass exec test-dotrun -- python3 -m unittest discover --verbose --start-directory ./dotrun/tests

multipass stop test-dotrun
