name: dotrun

version: "1.4.8"

summary: A command-line tool for running Node.js and Python projects

description: |
  A command-line tool for running Node.js and Python projects
  from Canonical's webteam

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  node:
    plugin: dump
    source:
      - on amd64: https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.15.1-deb-1nodesource1_amd64.deb
      - on arm64: https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.15.1-deb-1nodesource1_arm64.deb

  yarn:
    plugin: dump
    source: https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn_1.22.19_all.deb

  semwraplib:
    plugin: dump
    source: src
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      gcc -g -O0 -Wall -Wstrict-prototypes -fPIC -shared lib.c -o $SNAPCRAFT_PART_INSTALL/lib/semwraplib.so -ldl
    build-packages:
      - build-essential

  dotrun-module:
    plugin: python
    source: src
    python-packages:
      - docker-compose
    stage-packages:
      - curl
      - gettext
      - git
      - build-essential
      - python3-dev
      - libjpeg-dev
      - libjpeg-progs
      - libmagic1
      - libmagickwand-dev
      - libpng-dev
      - libpq-dev
      - libsodium-dev
      - gpg
      - optipng
      - zlib1g-dev
      # Chromium dependencies (for puppeteer NPM package)
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcups2
      - libdrm2
      - libgbm1
      - libnss3
      - libpango-1.0-0
      - libx11-6
      - libxau6
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxkbcommon-x11-0
      - libxrandr2
      - libwayland-client.so.0
plugs:
  dot-npmrc:
    interface: personal-files
    read:
      - $HOME/.npmrc
  dot-yarnrc:
    interface: personal-files
    read:
      - $HOME/.yarnrc
  docker-cli:
    interface: docker
  docker-executables:
    content: docker-executables
    default-provider: docker
    interface: content
    target: docker-env
  lxd:
    interface: lxd

apps:
  dotrun:
    command: bin/dotrun
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LC_CTYPE: C.UTF-8
      LD_PRELOAD: $SNAP/lib/semwraplib.so
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_CONFIG_NOSYSTEM: 1
    plugs:
      - home
      - network
      - network-bind
      - process-control
      - dot-npmrc
      - dot-yarnrc
      - docker-cli
      - docker-executables
      - desktop
