name: dotrun
base: core18
version: '1.0.0'
summary: A command-line tool for running Node.js and Python projects
description: |
  A command-line tool for running Node.js and Python projects
  from Canonical's webteam

grade: stable
confinement: strict

parts:
  node:
    plugin: dump
    source: https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.4.0-1nodesource1_amd64.deb

  yarn:
    plugin: dump
    source: https://github.com/yarnpkg/yarn/releases/download/v1.22.0/yarn_1.22.0_all.deb

  semwraplib:
    plugin: dump
    source: .
    override-build: |
      mkdir -p ../install/bin
      gcc -g -O0 -Wall -Wstrict-prototypes -fPIC -shared lib.c -o ../install/bin/semwraplib.so -ldl
    build-packages:
    - build-essential

  dotrun-module:
    plugin: python
    source: .
    stage-packages:
      - curl
      - git
      - libjpeg-progs
      - libmagickwand-dev
      - libpng-dev
      - libpq-dev
      - libsodium-dev
      - optipng
      - zlib1g-dev

apps:
  dotrun:
    command: dotrun
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LC_CTYPE: C.UTF-8
      LD_PRELOAD: $SNAP/bin/semwraplib.so
    plugs:
      - home
      - network
      - network-bind
      - process-control
