name: dotrun
base: core18

version: "1.4.1"

summary: A command-line tool for running Node.js and Python projects

description: |
  A command-line tool for running Node.js and Python projects
  from Canonical's webteam

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

parts:
  node:
    plugin: dump
    source:
      - on amd64: https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.8.0-deb-1nodesource1_amd64.deb
      - on arm64: https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.8.0-deb-1nodesource1_arm64.deb

  yarn:
    plugin: dump
    source: https://github.com/yarnpkg/yarn/releases/download/v1.22.0/yarn_1.22.0_all.deb

  semwraplib:
    plugin: dump
    source: src
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      gcc -g -O0 -Wall -Wstrict-prototypes -fPIC -shared lib.c -o $SNAPCRAFT_PART_INSTALL/lib/semwraplib.so -ldl
    build-packages:
      - build-essential

  dotrun-module:
    plugin: python
    source: src
    stage-packages:
      - curl
      - gettext
      - git
      - build-essential
      - python3-dev
      - libjpeg-dev
      - libjpeg-progs
      - libmagic1
      - libmagickwand-dev
      - libpng-dev
      - libpq-dev
      - libsodium-dev
      - gpg
      - optipng
      - zlib1g-dev

plugs:
  dot-npmrc:
    interface: personal-files
    read:
      - $HOME/.npmrc
  dot-yarnrc:
    interface: personal-files
    read:
      - $HOME/.yarnrc
  docker-cli:
    interface: docker
  docker-executables:
    content: docker-executables
    default-provider: docker
    interface: content
    target: docker-env

apps:
  dotrun:
    command: dotrun
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LC_CTYPE: C.UTF-8
      LD_PRELOAD: $SNAP/lib/semwraplib.so
      PYTHONPATH: $PYTHONPATH:/snap/docker/current/lib/python3.6/site-packages/
    plugs:
      - home
      - network
      - network-bind
      - process-control
      - dot-npmrc
      - dot-yarnrc
      - docker-cli
      - docker-executables
